language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn coverage
  - yarn build
after_success:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - build-storybook
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: ./storybook-static
  on:
    branch: master