language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn coverage
  - yarn build
after_success:
  - "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
  - build-storybook
  - yarn deploy
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
