language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
  - '7'
  - '6'
script:
  - yarn coverage
  - yarn build
after_success:
  - npm run semantic-release
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
